# enable labeler on issues, prs, or both.
enable:
  issues: false
  prs: true

comments:
  prs: |
    Labeler has applied any labels matching special text in your title and description.
    Please review the labels and make any necessary changes.

# 레이블
labels:
  "bug":
    include:
      - '\bbug[s]?\b'
    exclude: []
  "feature":
    include:
      - '\bfeat[s]?\b'
      - '\bfeature[s]?\b'
    exclude: []
