# enable labeler on issues, prs, or both.
enable:
  issues: false
  prs: true

comments:
  prs: |
    Labeler has applied any labels matching special text in your title and description.
    Please review the labels and make any necessary changes.

labels:
  "bug":
    include:
      - '\bbug\b'
      - '\bfix\b'
    exclude: []
  "feature":
    include:
      - '\bfeat\b'
      - '\bfeature\b'
      - '\badd\b'
    exclude: []
  "refactor":
    include:
      - '\brefactor\b'
      - '\brefactoring\b'
    exclude: []
  "documentation":
    include:
      - '\bdocs\b'
    exclude: []
  "chore":
    include:
      - '\bchore\b'
    exclude: []
  "test":
    include:
      - '\btest\b'
    exclude: []
