enable:
  - issues: false
  - prs: true

comments:
  - prs: Labeler has applied any labels matching special text in your title and description. Please review the labels and make any necessary changes.

labels:
  - name: bug
    pattern: '(?i)\[?\s*bugfix\s*\]?'
  - name: feature
    pattern: '(?i)\[?\s*feature\s*\]?'
  - name: refactor
    pattern: '(?i)\[?\s*refactor\s*\]?'
  - name: documentation
    pattern: '(?i)\[?\s*docs\s*\]?'
  - name: chore
    pattern: '(?i)\[?\s*chore\s*\]?'
  - name: test
    pattern: '(?i)\[?\s*test\s*\]?'
