enable:
  issues: false
  prs: true

comments:
  prs: |
    Labeler has applied any labels matching special text in your title and description.
    Please review the labels and make any necessary changes.

labels:
  "bug":
    include:
      - '(?i)\[?bug\]?'
      - '(?i)\[?fix\]?'
    exclude: []
  "feature":
    include:
      - '(?i)\[?feat\]?\b'
      - '(?i)\[?feature\]?\b'
      - '(?i)\[?add\]?\b'
    exclude: []
  "refactor":
    include:
      - '(?i)\[?refactor\]?\b'
      - '(?i)\[?refactoring\]?\b'
    exclude: []
  "documentation":
    include:
      - '(?i)\[?docs\]?\b'
    exclude: []
  "chore":
    include:
      - '(?i)\[?chore\]?\b'
    exclude: []
  "test":
    include:
      - '(?i)\[?test\]?\b'
    exclude: []
