# .github/labeler.yml

# enable labeler on issues, prs, or both.
enable:
  issues: false
  prs: true

comments:
  prs: |
    Labeler has applied any labels matching special text in your title and description.
    Please review the labels and make any necessary changes.

labels:
  "bug":
    include:
      - '(?i)\bbug\b'
      - '(?i)\bfix\b'
    exclude: []
  "feature":
    include:
      - '(?i)\bfeat\b'
      - '(?i)\bfeature\b'
      - '(?i)\badd\b'
    exclude: []
  "refactor":
    include:
      - '(?i)\brefactor\b'
      - '(?i)\brefactoring\b'
    exclude: []
  "documentation":
    include:
      - '(?i)\bdocs\b'
    exclude: []
  "chore":
    include:
      - '(?i)\bchore\b'
    exclude: []
  "test":
    include:
      - '(?i)\btest\b'
    exclude: []
