# .github/workflows/pr-labeler.yml
name: PR labeler

on:
  pull_request:
    types: [opened]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check Labels
        id: labeler
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{secrets.LABELER_TOKEN}}
