name: Auto Labeler and Review Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check Labels
        id: labeler
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  assign:
    runs-on: ubuntu-latest
    needs: labeler # Ensures that the assign job runs after the labeler job
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: rtm-goeun
