name: Auto Labeler and Review Assign

on:
  pull_request_target:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: rtm-goeun

  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: github.base_ref != 'main'
    steps:
      - name: Check Labels
        id: labeler
        uses: jimschubert/labeler-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
